// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs            = require("fs");
var $$Array       = require("bs-platform/lib/js/array.js");
var Process       = require("process");
var Caml_array    = require("bs-platform/lib/js/caml_array.js");
var Algoliasearch = require("algoliasearch");

var appId = "B1AVN0IGTU";

var apiKey = Caml_array.caml_array_get(Process.argv, 2);

var client = Algoliasearch(appId, apiKey);

var index = client.initIndex("re:libs");

$$Array.map((function (record) {
        index.addObject(record, (function (err, _) {
                console.log(err);
                return /* () */0;
              }));
        return /* () */0;
      }), $$Array.map((function (prim) {
            return JSON.parse(prim);
          }), $$Array.map((function (filename) {
                return Fs.readFileSync("data/generated/packages/" + filename, "utf8");
              }), Fs.readdirSync("data/generated/packages"))));

exports.appId  = appId;
exports.apiKey = apiKey;
exports.client = client;
exports.index  = index;
/* apiKey Not a pure module */
