// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Utils             = require("./Utils.js");
var Rebase            = require("reason-rebase/src/rebase.js");
var Source            = require("./Source.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function normalizeKeyword(keyword) {
  var keyword$1 = keyword.toLowerCase();
  if (keyword$1 === "reasonml") {
    return "reason";
  } else {
    return keyword$1;
  }
}

function fromPublished(data) {
  return {
          type: "published",
          id: data[/* name */1],
          name: data[/* name */1],
          version: data[/* version */2],
          description: data[/* description */3],
          author: Js_null_undefined.from_opt(data[/* author */5]),
          license: Js_null_undefined.from_opt(data[/* license */6]),
          keywords: Utils.filterDuplicates(Rebase.$$Array[/* map */2](normalizeKeyword, Rebase.Option[/* getOr */14](/* array */[], data[/* keywords */8]))),
          readme: Rebase.Option[/* getOr */14]("", data[/* readme */7]),
          analyzed: data[/* analyzed */0],
          updated: data[/* analyzed */0],
          stars: Js_null_undefined.from_opt(data[/* stars */9]),
          score: data[/* score */10],
          quality: data[/* quality */11],
          popularity: data[/* popularity */12],
          maintenance: data[/* maintenance */13],
          homepageUrl: Js_null_undefined.from_opt(data[/* homepageUrl */14]),
          repositoryUrl: Js_null_undefined.from_opt(data[/* repositoryUrl */15]),
          npmUrl: Js_null_undefined.from_opt(data[/* npmUrl */16]),
          issuesUrl: Js_null_undefined.from_opt(data[/* issuesUrl */17]),
          docsUrl: null
        };
}

function fromUnpublished(source, manifest, readme, stars) {
  return {
          type: "unpublished",
          id: Source.makeId(source),
          name: Source.makeName(source),
          version: manifest[/* version */1],
          description: Rebase.Option[/* getOr */14]("", manifest[/* description */2]),
          author: Js_null_undefined.from_opt(manifest[/* author */3]),
          license: Js_null_undefined.from_opt(manifest[/* license */4]),
          keywords: Utils.filterDuplicates(Rebase.$$Array[/* map */2](normalizeKeyword, Rebase.Option[/* getOr */14](/* array */[], manifest[/* keywords */5]))),
          readme: readme,
          analyzed: new Date(),
          updated: new Date(),
          stars: stars,
          score: 0,
          quality: 0,
          popularity: 0,
          maintenance: 0,
          homepageUrl: Js_null_undefined.from_opt(manifest[/* homepage */7]),
          repositoryUrl: Source.getRepositoryUrl(source),
          npmUrl: null,
          issuesUrl: Js_null_undefined.from_opt(manifest[/* bugsUrl */9]),
          docsUrl: null
        };
}

exports.normalizeKeyword = normalizeKeyword;
exports.fromPublished    = fromPublished;
exports.fromUnpublished  = fromUnpublished;
/* Utils Not a pure module */
