// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs      = require("fs");
var Path    = require("path");
var Rebase  = require("@glennsl/rebase/src/rebase.bs.js");
var Resync  = require("refetch/src/Resync.js");
var Hashtbl = require("bs-platform/lib/js/hashtbl.js");

function stick(x) {
  console.log(x);
  return x;
}

function readDirRecursively(dir) {
  return Rebase.$$Array[/* flatMap */5]((function (filename) {
                var path = Path.join(dir, filename);
                var match = +Fs.statSync(path).isDirectory();
                if (match !== 0) {
                  return readDirRecursively(path);
                } else {
                  return /* array */[path];
                }
              }), Fs.readdirSync(dir));
}

var Fs$1 = /* module */[/* readDirRecursively */readDirRecursively];

function filterDuplicates(arr) {
  var unique = /* array */[];
  var set = Hashtbl.create(/* None */0, arr.length);
  arr.forEach((function (x) {
          return Hashtbl.replace(set, x, /* () */0);
        }));
  Hashtbl.iter((function (x, _) {
          unique.push(x);
          return /* () */0;
        }), set);
  return unique;
}

function $great$great$eq($$this, f) {
  return Resync.Future[/* flatMap */9](f, $$this);
}

var $$return = Resync.Future[/* from */3];

var Future = /* module */[
  /* >>= */$great$great$eq,
  /* return */$$return
];

exports.stick            = stick;
exports.Fs               = Fs$1;
exports.filterDuplicates = filterDuplicates;
exports.Future           = Future;
/* fs Not a pure module */
